/* Datos mock realistas para el rediseño del Explore de Luderis */
window.LUDERIS = window.LUDERIS || {};

// Materias con su icono de línea (clave del registro de Icon)
window.LUDERIS.CATEGORIES = [
  { label: "Idiomas",                 icon: "languages",   accent: "curso" },
  { label: "Programación",            icon: "code",        accent: "curso" },
  { label: "Ciencia y Matemática",    icon: "flask",       accent: "curso" },
  { label: "Música",                  icon: "music",       accent: "pedido" },
  { label: "Arte y Diseño",           icon: "palette",     accent: "pedido" },
  { label: "Negocios y Finanzas",     icon: "briefcase",   accent: "curso" },
  { label: "Cocina",                  icon: "chef",        accent: "clase" },
  { label: "Deportes",                icon: "activity",    accent: "clase" },
  { label: "Apoyo escolar",           icon: "bookOpen",    accent: "curso" },
  { label: "Bienestar",               icon: "heart",       accent: "pedido" },
];

const A = (n, e) => ({ autor_nombre: n, autor_email: e });

// ── Docentes destacados ───────────────────────────────────────────────────
window.LUDERIS.TEACHERS = [
  { id: "t1", nombre: "María Belén Ríos", materias: ["Idiomas", "Inglés"],
    bio: "10 años enseñando inglés. Método comunicativo, material propio.",
    rating: 4.9, reviews: 127, ciudad: "Online", verificado: true,
    disponible_hoy: true, publicaciones: 3, alumnos: 340, accent: "curso" },
  { id: "t2", nombre: "Laura Giménez", materias: ["Matemática", "Álgebra"],
    bio: "Profesora de secundaria y CBC. Explico hasta que se entienda.",
    rating: 5.0, reviews: 53, ciudad: "Rosario", verificado: true,
    disponible_hoy: true, publicaciones: 2, alumnos: 95, accent: "clase" },
  { id: "t3", nombre: "Tomás Alderete", materias: ["Programación", "React"],
    bio: "Dev con 8 años de experiencia. Cursos orientados a portfolio.",
    rating: 4.8, reviews: 89, ciudad: "Online", verificado: true,
    disponible_hoy: false, publicaciones: 4, alumnos: 218, accent: "curso" },
  { id: "t4", nombre: "Carolina Méndez", materias: ["Diseño UX/UI", "Figma"],
    bio: "Diseñadora senior. Portfolio real, feedback honesto.",
    rating: 4.9, reviews: 71, ciudad: "Online", verificado: true,
    disponible_hoy: false, publicaciones: 2, alumnos: 130, accent: "curso" },
  { id: "t5", nombre: "Valentina Luna", materias: ["Apoyo escolar", "Primaria"],
    bio: "Maestra con vocación. Refuerzo de hábitos y preparación de pruebas.",
    rating: 5.0, reviews: 61, ciudad: "La Plata", verificado: true,
    disponible_hoy: true, publicaciones: 1, alumnos: 78, accent: "clase" },
  { id: "t6", nombre: "Ramiro Acosta", materias: ["Física", "CBC"],
    bio: "Ing. egresado del ITBA. Especialista en finales difíciles.",
    rating: 4.8, reviews: 47, ciudad: "Online", verificado: true,
    disponible_hoy: false, publicaciones: 2, alumnos: 88, accent: "clase" },
];

window.LUDERIS.POSTS = [
  {
    id: "p1", ...A("María Belén Ríos", "mbrios"), materia: "Idiomas",
    titulo: "Inglés conversacional para adultos — de cero a fluidez",
    descripcion: "Clases dinámicas centradas en hablar desde el día uno. Material propio y seguimiento personalizado de tu progreso.",
    tipo: "oferta", modo: "curso", modalidad: "virtual", sinc: "sinc",
    precio: 8500, moneda: "ARS", precio_tipo: "mes", nivel: "adultos",
    rating: 4.9, reviews: 127, vistas: 1840, inscriptos: 64, ciudad: "Online",
    verificado: true, disponible_hoy: true, nuevo: "", tiene_prueba: true,
  },
  {
    id: "p2", ...A("Tomás Alderete", "talderete"), materia: "Programación",
    titulo: "Desarrollo web full-stack con React y Node",
    descripcion: "Curso intensivo orientado a proyectos. Terminás con tres apps reales en tu portfolio y preparación para entrevistas.",
    tipo: "oferta", modo: "curso", modalidad: "virtual", sinc: "asinc",
    precio: 24000, moneda: "ARS", precio_tipo: "mes", nivel: "universitario",
    rating: 4.8, reviews: 89, vistas: 2310, inscriptos: 112, ciudad: "Online",
    verificado: true, disponible_hoy: false, nuevo: "NUEVO", tiene_prueba: false,
  },
  {
    id: "p3", ...A("Laura Giménez", "lgimenez"), materia: "Ciencia y Matemática",
    titulo: "Matemática para secundaria — álgebra y análisis",
    descripcion: "Preparación de exámenes y apoyo continuo. Explico hasta que se entienda, con ejercicios resueltos paso a paso.",
    tipo: "oferta", modo: "particular", modalidad: "mixto", sinc: "sinc",
    precio: 6000, moneda: "ARS", precio_tipo: "hora", nivel: "secundaria",
    rating: 5.0, reviews: 53, vistas: 920, inscriptos: 0, ciudad: "Rosario",
    verificado: true, disponible_hoy: true, nuevo: "", tiene_prueba: true,
  },
  {
    id: "p4", ...A("Diego Sosa", "dsosa"), materia: "Música",
    titulo: "Guitarra criolla y eléctrica — todos los niveles",
    descripcion: "Aprendé tus canciones favoritas mientras incorporás teoría sin que se vuelva aburrido. Primera clase de prueba gratis.",
    tipo: "oferta", modo: "particular", modalidad: "presencial", sinc: "sinc",
    precio: 5000, moneda: "ARS", precio_tipo: "hora", nivel: "todos",
    rating: 4.7, reviews: 38, vistas: 640, inscriptos: 0, ciudad: "CABA · Palermo",
    verificado: false, disponible_hoy: true, nuevo: "", tiene_prueba: true,
  },
  {
    id: "p5", ...A("Carolina Méndez", "cmendez"), materia: "Arte y Diseño",
    titulo: "Diseño UX/UI desde cero — portfolio incluido",
    descripcion: "Del wireframe al prototipo en Figma. Trabajamos sobre casos reales y armás un portfolio listo para postular.",
    tipo: "oferta", modo: "curso", modalidad: "virtual", sinc: "asinc",
    precio: 19500, moneda: "ARS", precio_tipo: "mes", nivel: "adultos",
    rating: 4.9, reviews: 71, vistas: 1530, inscriptos: 48, ciudad: "Online",
    verificado: true, disponible_hoy: false, nuevo: "NUEVO", tiene_prueba: false,
  },
  {
    id: "p6", ...A("Federico Paz", "fpaz"), materia: "Negocios y Finanzas",
    titulo: "Finanzas personales e inversiones para principiantes",
    descripcion: "Ordená tus finanzas, armá un presupuesto que funcione y entendé cómo empezar a invertir sin humo.",
    tipo: "oferta", modo: "curso", modalidad: "virtual", sinc: "sinc",
    precio: 12000, moneda: "ARS", precio_tipo: "mes", nivel: "adultos",
    rating: 4.6, reviews: 44, vistas: 1120, inscriptos: 37, ciudad: "Online",
    verificado: true, disponible_hoy: false, nuevo: "", tiene_prueba: false,
  },
  {
    id: "p7", ...A("Sofía Castro", "scastro"), materia: "Idiomas",
    titulo: "Portugués para viajar y trabajar en Brasil",
    descripcion: "Enfoque práctico para situaciones reales. Salís hablando lo necesario para defenderte en tu primer viaje.",
    tipo: "oferta", modo: "particular", modalidad: "virtual", sinc: "sinc",
    precio: 4500, moneda: "ARS", precio_tipo: "hora", nivel: "todos",
    rating: 4.8, reviews: 29, vistas: 510, inscriptos: 0, ciudad: "Online",
    verificado: false, disponible_hoy: true, nuevo: "", tiene_prueba: true,
  },
  {
    id: "p8", ...A("Martín Quiroga", "mquiroga"), materia: "Cocina",
    titulo: "Panadería casera: masa madre y bollería",
    descripcion: "Aprendé a hacer pan de verdad en tu cocina. Recetas, técnica y los secretos para que salga siempre.",
    tipo: "oferta", modo: "particular", modalidad: "presencial", sinc: "sinc",
    precio: 7000, moneda: "ARS", precio_tipo: "hora", nivel: "todos",
    rating: 4.9, reviews: 22, vistas: 430, inscriptos: 0, ciudad: "Córdoba",
    verificado: true, disponible_hoy: false, nuevo: "", tiene_prueba: false,
  },
  {
    id: "p9", ...A("Valentina Luna", "vluna"), materia: "Apoyo escolar",
    titulo: "Apoyo escolar primaria — todas las materias",
    descripcion: "Acompañamiento integral con paciencia y método. Refuerzo de hábitos de estudio y preparación de pruebas.",
    tipo: "oferta", modo: "particular", modalidad: "mixto", sinc: "sinc",
    precio: 3800, moneda: "ARS", precio_tipo: "hora", nivel: "primaria",
    rating: 5.0, reviews: 61, vistas: 780, inscriptos: 0, ciudad: "La Plata",
    verificado: true, disponible_hoy: true, nuevo: "", tiene_prueba: true,
  },
  {
    id: "p10", ...A("Nicolás Vera", "nvera"), materia: "Programación",
    titulo: "Python para análisis de datos y automatización",
    descripcion: "De los fundamentos a pandas y scripts útiles. Ideal si querés sumar datos a tu trabajo actual.",
    tipo: "oferta", modo: "curso", modalidad: "virtual", sinc: "asinc",
    precio: 16000, moneda: "ARS", precio_tipo: "mes", nivel: "adultos",
    rating: 4.7, reviews: 56, vistas: 1390, inscriptos: 73, ciudad: "Online",
    verificado: true, disponible_hoy: false, nuevo: "", tiene_prueba: false,
  },
  {
    id: "p11", ...A("Agustina Ferro", "aferro"), materia: "Bienestar",
    titulo: "Yoga y meditación para reducir el estrés",
    descripcion: "Clases suaves aptas para todo nivel. Mejorá tu flexibilidad, postura y descanso desde casa.",
    tipo: "oferta", modo: "particular", modalidad: "virtual", sinc: "sinc",
    precio: 4000, moneda: "ARS", precio_tipo: "hora", nivel: "todos",
    rating: 4.9, reviews: 34, vistas: 600, inscriptos: 0, ciudad: "Online",
    verificado: false, disponible_hoy: true, nuevo: "", tiene_prueba: true,
  },
  {
    id: "p12", ...A("Ramiro Acosta", "racosta"), materia: "Ciencia y Matemática",
    titulo: "Física universitaria — Mecánica y Electromagnetismo",
    descripcion: "Preparación de finales del CBC e ingenierías. Resolvemos parciales viejos y dudas conceptuales.",
    tipo: "oferta", modo: "particular", modalidad: "virtual", sinc: "sinc",
    precio: 6500, moneda: "ARS", precio_tipo: "hora", nivel: "universitario",
    rating: 4.8, reviews: 47, vistas: 880, inscriptos: 0, ciudad: "Online",
    verificado: true, disponible_hoy: false, nuevo: "", tiene_prueba: false,
  },

  /* ── Pedidos (alumnos buscando docentes) ── */
  {
    id: "b1", ...A("Julián Romero", "jromero"), materia: "Música",
    titulo: "Busco profe de piano para principiante adulto",
    descripcion: "Quiero arrancar de cero, una vez por semana, preferentemente presencial por zona Caballito.",
    tipo: "busqueda", modo: "particular", modalidad: "presencial",
    precio: 5000, moneda: "ARS", precio_tipo: "hora", nivel: "todos",
    ciudad: "CABA · Caballito", expira_dias: 5,
  },
  {
    id: "b2", ...A("Paula Ibáñez", "pibanez"), materia: "Idiomas",
    titulo: "Necesito preparar examen First de Cambridge",
    descripcion: "Tengo el examen en 3 meses. Busco alguien con experiencia en exámenes internacionales, online.",
    tipo: "busqueda", modo: "particular", modalidad: "virtual",
    precio: 6000, moneda: "ARS", precio_tipo: "hora", nivel: "adultos",
    ciudad: "Online", expira_dias: 12,
  },
  {
    id: "b3", ...A("Esteban Ledesma", "eledesma"), materia: "Programación",
    titulo: "Busco mentor para proyecto final de bootcamp",
    descripcion: "Necesito ayuda puntual con un proyecto en React. Sesiones de revisión de código, una o dos por semana.",
    tipo: "busqueda", modo: "particular", modalidad: "virtual",
    precio: 8000, moneda: "ARS", precio_tipo: "hora", nivel: "adultos",
    ciudad: "Online", expira_dias: 3,
  },
  {
    id: "b4", ...A("Camila Núñez", "cnunez"), materia: "Apoyo escolar",
    titulo: "Apoyo en química para mi hijo de 4° año",
    descripcion: "Busco profe con paciencia para clases semanales presenciales en zona norte del GBA.",
    tipo: "busqueda", modo: "particular", modalidad: "presencial",
    precio: 4500, moneda: "ARS", precio_tipo: "hora", nivel: "secundaria",
    ciudad: "San Isidro", expira_dias: 8,
  },
];
