
content = open('C:/Users/Salvador de Vedia/OneDrive/Luderis/src/MiCuentaPage.jsx', 'r', encoding='utf-8').read()

new_component = (
    "// --- ALERTAS BUSQUEDAS TAB ---\n"
    "function AlertasBusquedasTab({session}){\n"
    "  const [alertas,setAlertas]=useState([]);\n"
    "  const [loading,setLoading]=useState(true);\n"
    "  const [showForm,setShowForm]=useState(false);\n"
    "  const [materiaForm,setMateriaForm]=useState(\"\");\n"
    "  const [modalidadForm,setModalidadForm]=useState(\"\");\n"
    "  const [saving,setSaving]=useState(false);\n"
    "\n"
    "  const cargar=useCallback(async()=>{\n"
    "    try{\n"
    "      const data=await sb.getAlertasBusquedas(session.user.email,session.access_token);\n"
    "      setAlertas(data||[]);\n"
    "    }catch{setAlertas([]);}finally{setLoading(false);}\n"
    "  },[session.user.email,session.access_token]);// eslint-disable-line\n"
    "\n"
    "  useEffect(()=>{cargar();},[cargar]);\n"
    "\n"
    "  const crear=async()=>{\n"
    "    if(!materiaForm){toast(\"Selecciona una materia\",\"error\");return;}\n"
    "    setSaving(true);\n"
    "    try{\n"
    "      const materias=materiaForm?[materiaForm]:[];\n"
    "      await sb.insertAlertaBusqueda({\n"
    "        email:session.user.email,\n"
    "        usuario_id:session.user.id,\n"
    "        materias,\n"
    "        modalidad:modalidadForm||null,\n"
    "        activa:true,\n"
    "      },session.access_token);\n"
    "      setMateriaForm(\"\");setModalidadForm(\"\");setShowForm(false);\n"
    "      toast(\"Alerta creada. Te avisaremos cuando haya una busqueda en esa materia\",\"success\",4000);\n"
    "      cargar();\n"
    "    }catch(e){toast(\"Error al crear la alerta: \"+e.message,\"error\");}\n"
    "    finally{setSaving(false);}\n"
    "  };\n"
    "\n"
    "  const eliminar=async(id)=>{\n"
    "    try{\n"
    "      await sb.deleteAlertaBusqueda(id,session.access_token);\n"
    "      setAlertas(p=>p.filter(a=>a.id!==id));\n"
    "      toast(\"Alerta eliminada\",\"info\");\n"
    "    }catch{}\n"
    "  };\n"
    "\n"
    "  const toggleActiva=async(alerta)=>{\n"
    "    try{\n"
    "      await sb.updateAlertaBusqueda(alerta.id,{activa:!alerta.activa},session.access_token);\n"
    "      setAlertas(p=>p.map(a=>a.id===alerta.id?{...a,activa:!a.activa}:a));\n"
    "    }catch{}\n"
    "  };\n"
    "\n"
    "  return(\n"
    "    <div style={{fontFamily:FONT}}>\n"
    "      <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:16,padding:\"18px 20px\",marginBottom:20}}>\n"
    "        <div style={{display:\"flex\",justifyContent:\"space-between\",alignItems:\"flex-start\",gap:12,flexWrap:\"wrap\"}}>\n"
    "          <div>\n"
    "            <div style={{fontWeight:700,color:C.text,fontSize:16,marginBottom:4}}>\U0001f514 Alertas de busquedas</div>\n"
    "            <div style={{fontSize:13,color:C.muted,lineHeight:1.5}}>\n"
    "              Te notificamos cuando un alumno busca docente en tu materia.\n"
    "            </div>\n"
    "          </div>\n"
    "          <button onClick={()=>setShowForm(v=>!v)}\n"
    "            style={{background:C.accent,border:\"none\",borderRadius:20,color:\"#fff\",padding:\"9px 20px\",fontWeight:700,fontSize:13,cursor:\"pointer\",fontFamily:FONT,flexShrink:0}}>\n"
    "            + Agregar materia\n"
    "          </button>\n"
    "        </div>\n"
    "\n"
    "        {showForm&&(\n"
    "          <div style={{background:C.surface,border:`1px solid ${C.accent}33`,borderRadius:12,padding:\"16px\",marginTop:16}}>\n"
    "            <div style={{marginBottom:10}}>\n"
    "              <Label>Materia *</Label>\n"
    "              <select value={materiaForm} onChange={e=>setMateriaForm(e.target.value)}\n"
    "                style={{width:\"100%\",background:C.bg,border:`1px solid ${C.border}`,borderRadius:8,padding:\"9px 12px\",color:materiaForm?C.text:C.muted,fontSize:13,outline:\"none\",fontFamily:FONT,boxSizing:\"border-box\"}}>\n"
    "                <option value=\"\">Selecciona una materia...</option>\n"
    "                {MATERIAS.map(m=><option key={m} value={m}>{m}</option>)}\n"
    "              </select>\n"
    "            </div>\n"
    "            <div style={{marginBottom:14}}>\n"
    "              <Label>Modalidad (opcional)</Label>\n"
    "              <div style={{display:\"flex\",gap:6,flexWrap:\"wrap\"}}>\n"
    "                {[[\"\",\"Todas\"],[\"virtual\",\"Virtual\"],[\"presencial\",\"Presencial\"],[\"mixta\",\"Mixta\"]].map(([v,l])=>(\n"
    "                  <button key={v} onClick={()=>setModalidadForm(v)}\n"
    "                    style={{padding:\"6px 14px\",borderRadius:20,fontSize:12,cursor:\"pointer\",fontFamily:FONT,\n"
    "                      background:modalidadForm===v?C.accent:\"transparent\",color:modalidadForm===v?\"#fff\":C.muted,\n"
    "                      border:`1px solid ${modalidadForm===v?C.accent:C.border}`,fontWeight:modalidadForm===v?700:400,transition:\"all .12s\"}}>\n"
    "                    {l}\n"
    "                  </button>\n"
    "                ))}\n"
    "              </div>\n"
    "            </div>\n"
    "            <div style={{display:\"flex\",gap:8}}>\n"
    "              <button onClick={crear} disabled={saving||!materiaForm}\n"
    "                style={{background:C.accent,border:\"none\",borderRadius:20,color:\"#fff\",padding:\"9px 24px\",fontWeight:700,fontSize:13,cursor:saving?\"wait\":\"pointer\",fontFamily:FONT,opacity:saving||!materiaForm?0.6:1}}>\n"
    "                {saving?\"Guardando...\":\"Crear alerta\"}\n"
    "              </button>\n"
    "              <button onClick={()=>{setShowForm(false);setMateriaForm(\"\");setModalidadForm(\"\");}}\n"
    "                style={{background:\"none\",border:`1px solid ${C.border}`,borderRadius:20,color:C.muted,padding:\"9px 16px\",cursor:\"pointer\",fontFamily:FONT,fontSize:13}}>\n"
    "                Cancelar\n"
    "              </button>\n"
    "            </div>\n"
    "          </div>\n"
    "        )}\n"
    "      </div>\n"
    "\n"
    "      {loading?<Spinner/>:alertas.length===0?(\n"
    "        <div style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:14,padding:\"48px 24px\",textAlign:\"center\"}}>\n"
    "          <div style={{fontSize:40,marginBottom:12}}>\U0001f514</div>\n"
    "          <div style={{fontWeight:600,color:C.text,fontSize:15,marginBottom:8}}>Sin alertas de busquedas</div>\n"
    "          <div style={{color:C.muted,fontSize:13,marginBottom:20}}>Agrega materias para recibir notificaciones cuando un alumno busque docente en esa area.</div>\n"
    "          <button onClick={()=>setShowForm(true)}\n"
    "            style={{background:C.accent,border:\"none\",borderRadius:20,color:\"#fff\",padding:\"10px 24px\",fontWeight:600,fontSize:13,cursor:\"pointer\",fontFamily:FONT}}>\n"
    "            Agregar primera materia\n"
    "          </button>\n"
    "        </div>\n"
    "      ):(\n"
    "        <div style={{display:\"flex\",flexDirection:\"column\",gap:10}}>\n"
    "          {alertas.map(a=>{\n"
    "            const materiasList=Array.isArray(a.materias)?a.materias:(a.materia?[a.materia]:[]);\n"
    "            return(\n"
    "              <div key={a.id} style={{background:C.surface,border:`1px solid ${a.activa?C.accent+\"44\":C.border}`,borderLeft:`3px solid ${a.activa?C.accent:C.muted}`,borderRadius:12,padding:\"14px 16px\",display:\"flex\",gap:12,alignItems:\"center\",opacity:a.activa?1:0.6,transition:\"all .2s\"}}>\n"
    "                <div style={{flex:1,minWidth:0}}>\n"
    "                  <div style={{display:\"flex\",gap:6,flexWrap:\"wrap\",alignItems:\"center\"}}>\n"
    "                    {materiasList.length>0\n"
    "                      ?materiasList.map(m=><span key={m} style={{fontSize:13,fontWeight:700,color:C.text}}>{m}</span>)\n"
    "                      :<span style={{fontSize:13,color:C.muted,fontStyle:\"italic\"}}>Materia no especificada</span>\n"
    "                    }\n"
    "                    {a.modalidad\n"
    "                      ?<span style={{fontSize:11,background:C.accentDim,color:C.accent,borderRadius:20,padding:\"2px 9px\",fontWeight:600}}>{a.modalidad===\"virtual\"?\"Virtual\":a.modalidad===\"presencial\"?\"Presencial\":\"Mixta\"}</span>\n"
    "                      :<span style={{fontSize:11,background:C.bg,color:C.muted,borderRadius:20,padding:\"2px 9px\",border:`1px solid ${C.border}`}}>Todas las modalidades</span>\n"
    "                    }\n"
    "                  </div>\n"
    "                  <div style={{fontSize:11,color:C.muted,marginTop:4}}>Creada {fmtRel(a.created_at)}</div>\n"
    "                </div>\n"
    "                <div style={{display:\"flex\",gap:6,flexShrink:0,alignItems:\"center\"}}>\n"
    "                  <button onClick={()=>toggleActiva(a)}\n"
    "                    style={{fontSize:11,fontWeight:600,padding:\"4px 10px\",borderRadius:20,border:`1px solid ${a.activa?C.accent+\"40\":C.border}`,background:a.activa?C.accentDim:\"transparent\",color:a.activa?C.accent:C.muted,cursor:\"pointer\",fontFamily:FONT,whiteSpace:\"nowrap\"}}>\n"
    "                    {a.activa?\"Activa\":\"Pausada\"}\n"
    "                  </button>\n"
    "                  <button onClick={()=>eliminar(a.id)}\n"
    "                    style={{background:\"none\",border:`1px solid ${C.border}`,borderRadius:20,color:C.danger,padding:\"4px 10px\",cursor:\"pointer\",fontSize:11,fontFamily:FONT}}>\n"
    "                    Eliminar\n"
    "                  </button>\n"
    "                </div>\n"
    "              </div>\n"
    "            );\n"
    "          })}\n"
    "        </div>\n"
    "      )}\n"
    "    </div>\n"
    "  );\n"
    "}\n"
    "\n"
)

target = 'function AlertasTab({session}){'
idx = content.find(target)
if idx == -1:
    print('NOT FOUND')
else:
    content = content[:idx] + new_component + content[idx:]
    open('C:/Users/Salvador de Vedia/OneDrive/Luderis/src/MiCuentaPage.jsx', 'w', encoding='utf-8').write(content)
    print('Done, inserted at index', idx)
