-- ═══════════════════════════════════════════════════════════════════════════
-- ⚠️  PENDIENTE — la policy de abajo ROMPE LA APP si se aplica tal cual
--
-- Estas dos policies cierran agujeros reales (F1 y A2 de la auditoría 2026-08),
-- pero los flujos actuales dependen justamente de lo que abren. Aplicarlas sin
-- los cambios de código de abajo deja la app rota en silencio (los inserts van
-- con `.catch(()=>{})` en casi todos los call-sites).
--
-- Se detectó al verificar contra el código, DESPUÉS de comprobar que la
-- migración "aplica sin errores": aplicar limpio no es lo mismo que no romper.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── F1 · notificaciones — ✅ RESUELTO 2026-08-06 ───────────────────────────
-- Se implementó la RPC `notificar()` (20260806_notificar_rpc.sql) y se
-- restringió la policy (20260806_notificaciones_policy_insert.sql). Ambas
-- aplicadas en producción.

-- ── A2 · alertas_digest_queue: INSERT con `with check (true)` ──────────────
-- Hoy cualquier autenticado inserta filas de digest con el email de otro y
-- texto arbitrario, que smart-worker después despacha como email de Luderis.
--
-- POR QUÉ NO SE PUEDE APLICAR YA: es exactamente lo que hace `dispararAlertas`
-- (supabase.ts:1175) y PostFormModal.jsx:167 — al publicar, el cliente inserta
-- un digest para CADA usuario cuya alerta matchea. O sea, la feature usa el
-- agujero como mecanismo.
--
-- CAMBIO DE CÓDIGO NECESARIO: mover `dispararAlertas` a una edge function (ya
-- estaba pendiente por performance: hoy corre un bucle secuencial de llamadas a
-- la IA desde el navegador). Con el matching server-side, el insert lo hace
-- service_role y esta policy pasa a ser aplicable.

-- drop policy if exists "authenticated_insert_digest" on public.alertas_digest_queue;
-- create policy "digest insert propio" on public.alertas_digest_queue
--   for insert to authenticated
--   with check (usuario_email = (select auth.email()));
